Update emby.yml

diff --git a/.github/workflows/emby.yml b/.github/workflows/emby.yml
--- a/.github/workflows/emby.yml
+++ b/.github/workflows/emby.yml
@@ -56,12 +56,12 @@ jobs:
           sudo sleep 3m     
           docker ps
 
-          # if rclone lsf openlist:aliyundriveCrypt/self-hosted/emby/config/ --files-only | grep -q "system.xml"; then
-          #   if ! rclone delete openlist:aliyundriveCrypt/self-hosted/emby/config/system.xml -vv; then
-          #     echo "[WARNING] Failed to delete system.xml, skipping" >&2
-          #   fi
-          # fi
-          # sudo rclone copy openlist:aliyundriveCrypt/self-hosted/emby/system.xml openlist:aliyundriveCrypt/self-hosted/emby/config/ --ignore-errors -vv
+          if rclone lsf openlist:aliyundriveCrypt/self-hosted/emby/config/ --files-only | grep -q "system.xml"; then
+            if ! rclone delete openlist:aliyundriveCrypt/self-hosted/emby/config/system.xml -vv; then
+              echo "[WARNING] Failed to delete system.xml, skipping" >&2
+            fi
+          fi
+          sudo rclone copy openlist:aliyundriveCrypt/self-hosted/emby/system.xml openlist:aliyundriveCrypt/self-hosted/emby/config/ --ignore-errors -vv
 
           # sudo mkdir -p /openlist
           # sudo nohup rclone mount openlist: /openlist --allow-non-empty --no-gzip-encoding --umask 000 --allow-other --attr-timeout 10m --vfs-cache-mode full --vfs-cache-max-age 5m --vfs-read-chunk-size-limit 10G --buffer-size 100M --vfs-cache-max-size 10G &
