Update emby.yml

diff --git a/.github/workflows/emby.yml b/.github/workflows/emby.yml
--- a/.github/workflows/emby.yml
+++ b/.github/workflows/emby.yml
@@ -35,12 +35,12 @@ jobs:
       - name: rclone-run
         run: |
           sudo apt-get install fuse3
-          # if rclone lsf onedrive:self-hosted/emby/config/ --files-only | grep -q "system.xml"; then
-          #   if ! rclone delete onedrive:self-hosted/emby/config/system.xml -vv; then
-          #     echo "[WARNING] Failed to delete system.xml, skipping" >&2
-          #   fi
-          # fi
-          # sudo rclone copy onedrive:self-hosted/emby/system.xml onedrive:self-hosted/emby/config/ --ignore-errors -vv
+          if rclone lsf dropbox:self-hosted/emby/config/ --files-only | grep -q "system.xml"; then
+            if ! rclone delete dropbox:self-hosted/emby/config/system.xml -vv; then
+              echo "[WARNING] Failed to delete system.xml, skipping" >&2
+            fi
+          fi
+          sudo rclone copy dropbox:self-hosted/emby/system.xml dropbox:self-hosted/emby/config/ --ignore-errors -vv
           # sudo mkdir /onedrive
           # sudo nohup rclone mount onedrive: /onedrive --allow-non-empty --no-gzip-encoding --umask 000 --allow-other --attr-timeout 10m --vfs-cache-mode full --vfs-cache-max-age 5m --vfs-read-chunk-size-limit 10G --buffer-size 100M --vfs-cache-max-size 50G &
           sudo mkdir /dropbox
@@ -56,15 +56,15 @@ jobs:
           sudo sleep 3m     
           docker ps
 
-          if rclone lsf openlist:aliyundriveCrypt/self-hosted/emby/config/ --files-only | grep -q "system.xml"; then
-            if ! rclone delete openlist:aliyundriveCrypt/self-hosted/emby/config/system.xml -vv; then
-              echo "[WARNING] Failed to delete system.xml, skipping" >&2
-            fi
-          fi
-          sudo rclone copy openlist:aliyundriveCrypt/self-hosted/emby/system.xml openlist:aliyundriveCrypt/self-hosted/emby/config/ --ignore-errors -vv
+          # if rclone lsf openlist:aliyundriveCrypt/self-hosted/emby/config/ --files-only | grep -q "system.xml"; then
+          #   if ! rclone delete openlist:aliyundriveCrypt/self-hosted/emby/config/system.xml -vv; then
+          #     echo "[WARNING] Failed to delete system.xml, skipping" >&2
+          #   fi
+          # fi
+          # sudo rclone copy openlist:aliyundriveCrypt/self-hosted/emby/system.xml openlist:aliyundriveCrypt/self-hosted/emby/config/ --ignore-errors -vv
 
-          sudo mkdir -p /openlist
-          sudo nohup rclone mount openlist: /openlist --allow-non-empty --no-gzip-encoding --umask 000 --allow-other --attr-timeout 10m --vfs-cache-mode full --vfs-cache-max-age 5m --vfs-read-chunk-size-limit 10G --buffer-size 100M --vfs-cache-max-size 10G &
+          # sudo mkdir -p /openlist
+          # sudo nohup rclone mount openlist: /openlist --allow-non-empty --no-gzip-encoding --umask 000 --allow-other --attr-timeout 10m --vfs-cache-mode full --vfs-cache-max-age 5m --vfs-read-chunk-size-limit 10G --buffer-size 100M --vfs-cache-max-size 10G &
       - name: install cloudflared
         run: |
           sudo mkdir ~/.cloudflared/
@@ -113,9 +113,9 @@ jobs:
               fi
           done
           
-          echo "==========/openlist/aliyundriveCrypt/self-hosted/emby==========="
-          sudo ls /openlist/aliyundriveCrypt/self-hosted/emby
-          sudo ln -s /openlist/aliyundriveCrypt/self-hosted/emby /var/lib/emby
+          echo "==========/dropbox/self-hosted/emby==========="
+          sudo ls /dropbox/self-hosted/emby
+          sudo ln -s /dropbox/self-hosted/emby /var/lib/emby
           echo "==========/var/lib/emby==========="
           sudo ls /var/lib/emby
           # sudo chown -R emby:emby /var/lib/emby
