Update emby.yml

diff --git a/.github/workflows/emby.yml b/.github/workflows/emby.yml
--- a/.github/workflows/emby.yml
+++ b/.github/workflows/emby.yml
@@ -41,10 +41,22 @@ jobs:
           #   fi
           # fi
           # sudo rclone copy dropbox:self-hosted/emby/system.xml dropbox:self-hosted/emby/config/ --ignore-errors -vv
+          if rclone lsf gd:self-hosted/emby/config/ --files-only | grep -q "system.xml"; then
+            if ! rclone delete gd:self-hosted/emby/config/system.xml -vv; then
+              echo "[WARNING] Failed to delete system.xml, skipping" >&2
+            fi
+          fi
+          sudo rclone copy gd:self-hosted/emby/system.xml gd:self-hosted/emby/config/ --ignore-errors -vv
+
+          # sudo mkdir -p /openlist
+          # sudo nohup rclone mount openlist: /openlist --vfs-cache-mode full &
           # sudo mkdir /onedrive
           # sudo nohup rclone mount onedrive: /onedrive --allow-non-empty --no-gzip-encoding --umask 000 --allow-other --attr-timeout 10m --vfs-cache-mode full --vfs-cache-max-age 5m --vfs-read-chunk-size-limit 10G --buffer-size 100M --vfs-cache-max-size 50G &
           sudo mkdir /dropbox
           sudo nohup rclone mount dropbox: /dropbox --allow-non-empty --no-gzip-encoding --umask 000 --allow-other --attr-timeout 10m --vfs-cache-mode full --vfs-cache-max-age 5m --vfs-read-chunk-size-limit 10G --buffer-size 100M --vfs-cache-max-size 50G &
+          sudo mkdir /gd
+          sudo nohup rclone mount gd: /gd --allow-non-empty --no-gzip-encoding --umask 000 --allow-other --attr-timeout 10m --vfs-cache-mode full --vfs-cache-max-age 5m --vfs-read-chunk-size-limit 10G --buffer-size 100M --vfs-cache-max-size 50G &
+
           # sudo rclone sync dropbox:self-hosted/emby /var/lib/emby -vv
           echo "==========onedrive==========="
           rclone lsf onedrive:
@@ -64,8 +76,7 @@ jobs:
           # sudo rclone copy openlist:aliyundriveCrypt/self-hosted/emby/system.xml openlist:aliyundriveCrypt/self-hosted/emby/config/ --ignore-errors -vv
 
           # sudo mkdir -p /openlist
-          # sudo nohup rclone mount openlist: /openlist --allow-non-empty --no-gzip-encoding --umask 000 --allow-other --attr-timeout 10m --vfs-cache-mode full --vfs-cache-max-age 5m --vfs-read-chunk-size-limit 10G --buffer-size 100M --vfs-cache-max-size 10G &
-          rclone sync dropbox:self-hosted/emby gd:self-hosted/emby -vv
+          # sudo nohup rclone mount openlist: /openlist --vfs-cache-mode full &
       - name: install cloudflared
         run: |
           sudo mkdir ~/.cloudflared/
@@ -114,12 +125,15 @@ jobs:
               fi
           done
           
+          # echo "==========/gd/self-hosted/emby==========="
+          # sudo ls /gd/self-hosted/emby
+          # sudo ln -s /gd/self-hosted/emby /var/lib/emby
           # echo "==========/dropbox/self-hosted/emby==========="
           # sudo ls /dropbox/self-hosted/emby
           # sudo ln -s /dropbox/self-hosted/emby /var/lib/emby
-          echo "==========/openlist/aliyundriveCrypt/self-hosted/emby==========="
-          sudo ls /openlist/aliyundriveCrypt/self-hosted/emby
-          sudo ln -s /openlist/aliyundriveCrypt/self-hosted/emby /var/lib/emby
+          # echo "==========/openlist/aliyundriveCrypt/self-hosted/emby==========="
+          # sudo ls /openlist/aliyundriveCrypt/self-hosted/emby
+          # sudo ln -s /openlist/aliyundriveCrypt/self-hosted/emby /var/lib/emby
           echo "==========/var/lib/emby==========="
           sudo ls /var/lib/emby
           # sudo chown -R emby:emby /var/lib/emby
