Update openlist.yml

diff --git a/.github/workflows/openlist.yml b/.github/workflows/openlist.yml
--- a/.github/workflows/openlist.yml
+++ b/.github/workflows/openlist.yml
@@ -3,7 +3,7 @@ name: openlist
 on:
   schedule:
     # - cron: "0 1,7,13,19 * * *"
-    - cron: "*/360 * * * *"
+    - cron: "*/5 * * * *"
   workflow_dispatch:
   # workflow_run:
   #   workflows:
@@ -18,21 +18,21 @@ jobs:
     runs-on: ubuntu-latest
     # timeout-minutes: 60
     steps:
-      # - name: Check Workflow Status
-      #   run: |
-      #     workflow_runs=$(curl -s -X GET \
-      #       -H "Accept: application/vnd.github.v3+json" \
-      #       -H "Authorization: Bearer ${{ secrets.PAT }}" \
-      #       "https://api.github.com/repos/${{ github.repository }}/actions/runs")
+      - name: Check Workflow Status
+        run: |
+          workflow_runs=$(curl -s -X GET \
+            -H "Accept: application/vnd.github.v3+json" \
+            -H "Authorization: Bearer ${{ secrets.PAT }}" \
+            "https://api.github.com/repos/${{ github.repository }}/actions/runs")
           
-      #     isRunning=$(echo "$workflow_runs" | jq '.workflow_runs[] | select(.name == "openlist" and .status == "in_progress")')
+          isRunning=$(echo "$workflow_runs" | jq '.workflow_runs[] | select(.name == "openlist" and .status == "in_progress")')
           
-      #     if [[ -n $isRunning ]]; then
-      #       echo "Another workflow is already running. Aborting current workflow."
-      #       exit 31
-      #     else
-      #       echo "No running workflows found. Continuing with the workflow execution."
-      #     fi
+          if [[ -n $isRunning ]]; then
+            echo "Another workflow is already running. Aborting current workflow."
+            exit 31
+          else
+            echo "No running workflows found. Continuing with the workflow execution."
+          fi
       - name: rclone-install
         run: |
           # 安装 rclone
